resources:
  - name: src
    type: git
    source:
      uri: https://github.com/seadowg/walkerman.git
      branch: master

  - name: pws
    type: cf
    source:
      api:
      username:
      password:
      organization:
      space: 
      skip_cert_check: false

jobs:
  - name: deploy
    plan:
      - get: src
      - task: package
        file: src/concourse/package.yml
      - put: pws
        params:
          manifest: package/src/manifest.yml

