resources:
  - name: walkerman
    type: git
    source:
      uri: https://github.com/seadowg/walkerman.git
      branch: master

jobs:
  - name: test
    plan:
      - get: walkerman
      - task: test
        file: walkerman/concourse/test.yml
