#!/bin/bash

# Setup terminal for gradle
export TERM=dumb

# Start postgres and create database
mkdir postgres
/usr/lib/postgresql/9.4/bin/initdb -U vcap -D ./postgres
/usr/lib/postgresql/9.4/bin/pg_ctl -D ./postgres -l logfile start
createdb walkerman

# Run testsb
cd walkerman
./gradlew test
